[project]
name = "python-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mixer>=7.2.2",
    "pygame>=2.6.1",
]
